print("Nume Prenume")
print("Babuta Luminita") 
print("Data luna anul nasterii")
print("06.08.2004") 
print("Date de contact")
print("+373078996232") 
print("luminita.babuta@mail.ru") 
print("Studiile")
print("2011-2015 scoala primara Spiridon Vangheli") 
print("2015-prezent Institutia Publica Liceul Teoretic Mihai Eminescu")
print("Calitati/abilitati")
print("straduitoare, perseverenta, desteapta, gandire critica bine dezvoltata")
print("Hobby")
print("artele plastice, recital de poezie, voluntariat")